version: '3.8'
services:
  web:
    build: .
    volumes:
      - ./coursework:/code
    ports:
      - "8050:8050"
    env_file:
      - .env
    depends_on:
      course_db:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8050
  course_db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pg-db:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pg-db:

