# Generated by Django 5.0.2 on 2024-02-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_club', '0002_alter_group_coach_alter_instructor_sportsman_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourist',
            name='qualification',
        ),
        migrations.AddField(
            model_name='amateur',
            name='qualification',
            field=models.IntegerField(choices=[(1, 'Початкова'), (2, 'Середня'), (3, 'Висока')], default=1),
        ),
    ]
