# Generated by Django 5.0.2 on 2024-02-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_club', '0003_remove_tourist_qualification_amateur_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=20),
        ),
        migrations.AlterField(
            model_name='manager',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=20),
        ),
    ]
